# Generated by Django 4.2.16 on 2024-09-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_note_file_fileversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileversion',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
